/********************************************************************************
This code is automatically generated by the VerticalThings compiler. DO NOT EDIT!
********************************************************************************/
#include <arduino.h>
#include "arduino.h"
/*Managed memory variables*/
unsigned char __vtmem[140];
int16_t (*test_mod2_factors_p)[10]= (int16_t (*)[10]) &__vtmem[0];
#define test_mod2_factors (*test_mod2_factors_p)
int (*test_mod2_rdata_p)[10]= (int (*)[10]) &__vtmem[20];
#define test_mod2_rdata (*test_mod2_rdata_p)
int (*test_mod_acquire_ybuf_p)[10]= (int (*)[10]) &__vtmem[60];
#define test_mod_acquire_ybuf (*test_mod_acquire_ybuf_p)
int (*test_mod_acquire_zbuf_p)[10]= (int (*)[10]) &__vtmem[100];
#define test_mod_acquire_zbuf (*test_mod_acquire_zbuf_p)
/*End of managed memory variables*/
/*Module vars for test_mod*/
int8_t test_mod_x, test_mod_y;
const int test_mod_modelData[10][10]={ { 1, 2, 3, 4, 5, 6, 7, 8, 9, 10} , { 1, 2, 3, 4, 5, 6, 7, 8, 9, 10} , { 1, 2, 3, 4, 5, 6, 7, 8, 9, 10} , { 1, 2, 3, 4, 5, 6, 7, 8, 9, 10} , { 1, 2, 3, 4, 5, 6, 7, 8, 9, 10} , { 1, 2, 3, 4, 5, 6, 7, 8, 9, 10} , { 1, 2, 3, 4, 5, 6, 7, 8, 9, 10} , { 1, 2, 3, 4, 5, 6, 7, 8, 9, 10} , { 1, 2, 3, 4, 5, 6, 7, 8, 9, 10} , { 1, 2, 3, 4, 5, 6, 7, 8, 9, 10} } ;
/*End of module vars for test_mod*/
int test_mod_acquire___pos_rbuf = 0;
int test_mod_acquire___pos_zbuf = 0;
/*Module vars for arduino*/
/*End of module vars for arduino*/
/*Module vars for test_mod2*/
int test_mod2___pos_rdata = 0;
/*End of module vars for test_mod2*/
int (*test_mod2_process_data_p)[10];
#define test_mod2_process_data (*test_mod2_process_data_p)
int test_mod2_process___pos_data
typedef enum { __test_mod_acquire, __test_mod2_process}  __icane_test;
 __icane_test __state = __test_mod_acquire;
void _test_mod_init()
{
    {
        test_mod_x=3;
    }
}
void _test_mod_acquire()
{
    const int test_mod_acquire_size=10;
    int __t0;
    int __t1;
    {
        pinPeripheral(3);
        for(int __i=0; __i<10; __i++)
        {
            __t0=0;
            for(int __j=0; __j<10; __j++)
            {
                __t0=((test_mod_modelData[__i][__j]*test_mod_acquire_rbuf[ ( (__j) + test_mod_acquire___pos_rbuf) % 10])+__t0);
            }
        }
        for(int __i=0; __i<[object Object]; __i++)
        {
            test_mod_acquire_ybuf[__i]=__t0;
        }
        for(int __i=0; __i<10; __i++)
        {
            __t1=0;
            for(int __j=0; __j<10; __j++)
            {
                __t1=((test_mod_modelData[__i][__j]*test_mod_acquire_ybuf[__j])+__t1);
            }
        }
        for(int __i=0; __i<[object Object]; __i++)
        {
            test_mod_acquire_zbuf[ ( (__i) + test_mod_acquire___pos_zbuf) % 10]=__t1;
        }
        test_mod2_process_data_p = &(test_mod_acquire_zbuf); test_mod2_process___pos_data = test_mod_acquire___pos_zbuf;__state = __test_mod2_process;
    }
}
int _test_mod2_compute(int test_mod2_compute_val[10], int test_mod2_compute_scale)
{
    int test_mod2_compute_result;
    float test_mod2_compute_fresult;
    int __t0;
    {
        test_mod2_compute_fresult=(float(test_mod2_compute_result));
        __t0=0;
        for(int __i=0; __i<10; __i++)
        {
            __t0=((test_mod2_compute_val[__i]*test_mod2_factors[__i])+__t0);
        }
        test_mod2_compute_result=(__t0+test_mod2_compute_scale);
        return test_mod2_compute_result;
    }
}
int _test_mod2_compute2(int test_mod2_compute2_value[10], int test_mod2_compute2___pos_value)
{
    {
        (test_mod2_compute2_value[test_mod2_compute2___pos_value = (test_mod2_compute2___pos_value + 1 == 10 ? 0: test_mod2_compute2___pos_value + 1)] = 10);
        test_mod2_compute2_value[ ( (0) + test_mod2_compute2___pos_value) % 10]=1;
    }
}
void _test_mod2_process()
{
    const int test_mod2_process_x=3;
    {
        _test_mod2_compute(test_mod2_process_data, test_mod2_process___pos_data, test_mod2_process_x);
        _test_mod2_compute2(test_mod2_rdata, test_mod2___pos_rdata);
    }
}
void loop()
{
    switch(__state)
    {
        case __test_mod_acquire:
        __state = __test_mod_acquire;
        _test_mod_acquire();
        break;
        case __test_mod2_process:
        __state = __test_mod_acquire;
        _test_mod2_process();
        break;
        default :
        __state = __test_mod_acquire;
    }
}
void setup()
{
    _test_mod_init();
}