module.exports = [
	__dirname + "/vtcompiler.js"
,	__dirname + "/astbuilder.js"
, 	__dirname + "/ast_util.js"
, 	__dirname + "/stdalloc.js"
, 	__dirname + "/pseq.js"
, 	__dirname + "/duseq.js"
, 	__dirname + "/stdalloc.js"
, 	__dirname + "/symtbl.js"
, 	__dirname + "/dynscope.js"
,   __dirname + "/CodeGen/matrixExprSimplify.js"	
,   __dirname + "/CodeGen/loopGen.js"		
,   __dirname + "/CodeGen/loopMerge.js"			
, 	__dirname + "/codegen.js"
, 	__dirname + "/codepp.js"
]